version: '3.4'

services:
  demo:
    image: demo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 8080:8080
      - 3006:3006
      - 3007:3007
